ERROR 2024-07-19 08:18:45,252 log 35944 35920 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static'. Did you forget to register or load this tag?
ERROR 2024-07-19 08:18:45,260 basehttp 35944 35920 "GET /dashboard/ HTTP/1.1" 500 181527
ERROR 2024-07-19 08:20:20,134 log 34528 9656 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static'. Did you forget to register or load this tag?
ERROR 2024-07-19 08:20:20,139 basehttp 34528 9656 "GET /dashboard/ HTTP/1.1" 500 181527
ERROR 2024-07-19 08:21:10,974 log 30800 20224 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:21:10,982 basehttp 30800 20224 "GET /dashboard/ HTTP/1.1" 500 180178
ERROR 2024-07-19 08:22:01,861 log 26004 27848 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:01,868 basehttp 26004 27848 "GET /dashboard/ HTTP/1.1" 500 180053
ERROR 2024-07-19 08:22:02,558 log 26004 3676 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:02,565 basehttp 26004 3676 "GET /dashboard/ HTTP/1.1" 500 180053
ERROR 2024-07-19 08:22:02,850 log 26004 25460 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:02,944 log 26004 34384 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:02,948 basehttp 26004 34384 "GET /dashboard/ HTTP/1.1" 500 180053
ERROR 2024-07-19 08:22:03,292 log 26004 24556 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:03,295 basehttp 26004 24556 "GET /dashboard/ HTTP/1.1" 500 180053
ERROR 2024-07-19 08:22:49,625 log 26004 22132 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:49,628 basehttp 26004 22132 "GET /dashboard/ HTTP/1.1" 500 179759
ERROR 2024-07-19 08:22:52,130 log 26004 22132 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:22:52,133 basehttp 26004 22132 "GET /dashboard/ HTTP/1.1" 500 179619
ERROR 2024-07-19 08:23:00,399 log 25792 31004 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:23:00,407 basehttp 25792 31004 "GET /dashboard/ HTTP/1.1" 500 179619
ERROR 2024-07-19 08:24:12,554 log 36272 34468 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:24:12,562 basehttp 36272 34468 "GET /dashboard/ HTTP/1.1" 500 179673
ERROR 2024-07-19 08:24:48,464 log 32492 18980 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:24:48,477 basehttp 32492 18980 "GET /dashboard/ HTTP/1.1" 500 179748
ERROR 2024-07-19 08:24:53,093 log 32492 18980 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 94, in dashboard_view
    return render(request, 'accounts/dashboard.html')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'title' appears more than once
ERROR 2024-07-19 08:24:53,096 basehttp 32492 18980 "GET /dashboard/ HTTP/1.1" 500 179748
ERROR 2024-07-19 09:20:58,747 log 8972 3264 Internal Server Error: /logout/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 100, in logout_view
    return render('accounts/login.html')
TypeError: render() missing 1 required positional argument: 'template_name'
ERROR 2024-07-19 09:20:58,748 basehttp 8972 3264 "GET /logout/ HTTP/1.1" 500 70455
ERROR 2024-07-21 12:53:28,206 log 30792 42152 Internal Server Error: /groups/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\accounts\views.py", line 58, in group_list
    return render(request, 'accounts/group_list.html', context=context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\template\base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'footer.html'> must be the first tag in the template.
ERROR 2024-07-21 12:53:28,222 basehttp 30792 42152 "GET /groups/ HTTP/1.1" 500 176030
ERROR 2024-07-23 20:41:37,712 log 22672 9120 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 169, in create_new_object
    qs.article_file.save(x, ContentFile(f.read()))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\fields\files.py", line 99, in save
    self.instance.save()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\model\article.py", line 76, in save
    if self.file_name_on_local_storage in ('', None):
AttributeError: 'Article_attributes' object has no attribute 'file_name_on_local_storage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 320, in jsonify_file_content
    create_new_object(json_file_name, row, "success")
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 175, in create_new_object
    Article_attributes.objects.create(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\model\article.py", line 76, in save
    if self.file_name_on_local_storage in ('', None):
AttributeError: 'Article_attributes' object has no attribute 'file_name_on_local_storage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 169, in create_new_object
    qs.article_file.save(x, ContentFile(f.read()))
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\fields\files.py", line 99, in save
    self.instance.save()
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\model\article.py", line 76, in save
    if self.file_name_on_local_storage in ('', None):
AttributeError: 'Article_attributes' object has no attribute 'file_name_on_local_storage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 352, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 287, in unzip_file
    jsonify_file_content(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 328, in jsonify_file_content
    create_new_object(json_file_name, row, e)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 175, in create_new_object
    Article_attributes.objects.create(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\model\article.py", line 76, in save
    if self.file_name_on_local_storage in ('', None):
AttributeError: 'Article_attributes' object has no attribute 'file_name_on_local_storage'
ERROR 2024-07-23 20:41:37,712 basehttp 22672 9120 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 192091
ERROR 2024-07-23 20:56:05,803 log 22692 27520 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 73, in read_xml_file
    return xmltodict.parse(xml_txt, encoding='utf-8')
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 35, column 664

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'date_stamp' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 352, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 287, in unzip_file
    jsonify_file_content(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 299, in jsonify_file_content
    json_data = is_article_tag_available(source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 94, in is_article_tag_available
    doc = read_xml_file(xml_file_path)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\article.py", line 78, in read_xml_file
    Unreadable_xml_files.objects.create(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\models\sql\compiler.py", line 1820, in execute_sql
    cursor.execute(sql, params)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'date_stamp' in 'field list'")
ERROR 2024-07-23 20:56:05,803 basehttp 22692 27520 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 262615
ERROR 2024-07-23 20:59:34,093 log 1796 1216 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 186, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 154, in unzip_file
    process_file(row, source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 56, in process_file
    with open(row.file_content, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not FieldFile
ERROR 2024-07-23 20:59:34,101 basehttp 1796 1216 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 115795
ERROR 2024-07-23 21:00:57,094 log 1796 1216 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 186, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 154, in unzip_file
    process_file(row, new_source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 56, in process_file
    with open(row.file_content, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not FieldFile
ERROR 2024-07-23 21:00:57,097 basehttp 1796 1216 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 115469
ERROR 2024-07-23 21:02:05,427 log 17448 13620 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 186, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 154, in unzip_file
    process_file(row, new_source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 56, in process_file
    with open(source, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not FieldFile
ERROR 2024-07-23 21:02:05,427 basehttp 17448 13620 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 115466
ERROR 2024-07-23 21:03:15,707 log 23184 22868 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 186, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 154, in unzip_file
    process_file(row, new_source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 59, in process_file
    result, message = splitter(content)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\splitter.py", line 129, in splitter
    list_of_articles, message = split_xml(data_xml, document_string)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\splitter.py", line 85, in split_xml
    if not message == 'successful':
UnboundLocalError: local variable 'message' referenced before assignment
ERROR 2024-07-23 21:03:15,715 basehttp 23184 22868 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 137720
ERROR 2024-07-23 21:10:19,824 log 23184 24928 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 186, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 154, in unzip_file
    process_file(row, new_source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 59, in process_file
    result, message = splitter(content)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\splitter.py", line 129, in splitter
    list_of_articles, message = split_xml(data_xml, document_string)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\splitter.py", line 85, in split_xml
    if not message == 'successful':
UnboundLocalError: local variable 'message' referenced before assignment
ERROR 2024-07-23 21:10:19,832 basehttp 23184 24928 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 137720
ERROR 2024-07-23 21:11:44,384 log 1236 17192 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 186, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 154, in unzip_file
    process_file(row, new_source)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files.py", line 59, in process_file
    result, message = splitter(content)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\splitter.py", line 129, in splitter
    list_of_articles, message = split_xml(data_xml, document_string)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\splitter.py", line 85, in split_xml
    if not message == 'successful':
UnboundLocalError: local variable 'message' referenced before assignment
ERROR 2024-07-23 21:11:44,399 basehttp 1236 17192 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 137747
ERROR 2024-07-23 22:21:06,933 log 13604 19448 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 357, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 302, in unzip_file
    process_xml_file(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 323, in process_xml_file
    if not is_mulitple_record(row.file_content.name, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 237, in is_mulitple_record
    with open(xml_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'CSIRO/543.ZIP'
ERROR 2024-07-23 22:21:06,949 basehttp 13604 19448 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 124014
ERROR 2024-07-23 22:22:24,885 log 13604 19448 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 357, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 302, in unzip_file
    process_xml_file(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 323, in process_xml_file
    if not is_mulitple_record(row.file_content.name, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 237, in is_mulitple_record
    with open(xml_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'CSIRO/543.ZIP'
ERROR 2024-07-23 22:22:24,885 basehttp 13604 19448 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 124059
ERROR 2024-07-23 22:24:48,767 log 28068 20248 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 356, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 301, in unzip_file
    process_xml_file(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 322, in process_xml_file
    if not is_mulitple_record(row.file_content.name, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 237, in is_mulitple_record
    with open(xml_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'CSIRO/543.ZIP'
ERROR 2024-07-23 22:24:48,783 basehttp 28068 20248 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 128723
ERROR 2024-07-23 22:26:48,084 log 28068 20248 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 356, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 301, in unzip_file
    process_xml_file(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 322, in process_xml_file
    if not is_mulitple_record(source, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 237, in is_mulitple_record
    with open(xml_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'CSIRO/543.ZIP'
ERROR 2024-07-23 22:26:48,093 basehttp 28068 20248 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 123999
ERROR 2024-07-23 22:27:03,083 log 15792 27636 Internal Server Error: /step2/migrate-to-step2/
Traceback (most recent call last):
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "e:\NAL-USDA\NAL_LIBRARY_SYSTEM\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 356, in migrate_to_step2
    if unzip_file(source, destination, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 301, in unzip_file
    process_xml_file(new_source, row)
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 322, in process_xml_file
    if not is_mulitple_record(source, row):
  File "E:\NAL-USDA\NAL_LIBRARY_SYSTEM\step2\process_files_self.py", line 239, in is_mulitple_record
    root = ET.fromstring(f.read())
  File "C:\Users\prasenjit\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1342, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 16, column 21
ERROR 2024-07-23 22:27:03,084 basehttp 15792 27636 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 131313
ERROR 2024-07-23 22:28:11,072 basehttp 15792 27636 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 131268
ERROR 2024-07-23 22:39:48,325 basehttp 20412 27636 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 154147
ERROR 2024-07-23 22:40:48,518 basehttp 17044 15804 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 124395
ERROR 2024-07-23 22:42:01,349 basehttp 17044 15804 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 124467
ERROR 2024-07-23 22:42:07,056 basehttp 18896 5740 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 124467
ERROR 2024-07-23 22:42:42,621 basehttp 18896 21548 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 122085
ERROR 2024-07-23 22:43:16,284 basehttp 6892 2776 "GET /step2/migrate-to-step2/ HTTP/1.1" 500 124497
